"""criacao inicial com usuarios produtos historico precos e alertas

Revision ID: 47faa2d11e25
Revises: 
Create Date: 2026-09-02 12:33:53.896680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47faa2d11e25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('loja', sa.String(length=100), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_nome'), ['nome'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)

    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('preco_alvo', sa.Float(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('disparado', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alertas_id'), ['id'], unique=False)

    op.create_table('historico_precos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('coletado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historico_precos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historico_precos_coletado_em'), ['coletado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_historico_precos_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_precos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historico_precos_id'))
        batch_op.drop_index(batch_op.f('ix_historico_precos_coletado_em'))

    op.drop_table('historico_precos')
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alertas_id'))

    op.drop_table('alertas')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_nome'))
        batch_op.drop_index(batch_op.f('ix_produtos_id'))

    op.drop_table('produtos')
    # ### end Alembic commands ###
